<?php

namespace AppBundle\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use AppBundle\Entity\Job;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Form\AddJobType;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;


class AddJobController extends Controller
{
    /**
     * @Route("/add_job", name="addjob")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */

    public function AddJobAction (Request $request)
    {
// creates a user and gives it some dummy data for this example
        $user = $this->getUser();
        $job = new Job();
        $form = $this->createForm(AddJobType::class, $job);
        $form->handleRequest($request);
        $job->Users=$user;
        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file
            // $file stores the uploaded PDF file
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $job->getImage();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('image_job_directory'),
                $fileName
            );

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $job->setImage($fileName);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($job);
            $entityManager->flush();
            return $this->redirectToRoute('home');
        }
        return $this->render('add_job/index.html.twig', array(
            'controller_name' => 'AddJobController',
            'form' => $form->createView(),
        ));
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


}
