easy_admin:
   entities:
#        # List the entity class name you want to manage
        - App\Entity\Backpacker
        - App\Entity\Hotes
        - App\Entity\Langue
        - App\Entity\Pays
        - App\Entity\Service
        - App\Entity\TypeService


